image: Visual Studio 2019

platform:
  - x64

cache:
  - node_modules -> package.json
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 14 x64
  - git submodule update --init --recursive
  - npm install --force

build_script:
  - npm test

test: false
