
jobs:
  include:
      os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"

cache:
  yarn: true
  directories:
    - node_modules

before_install: git pull

script:
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release@13"
  on:
    tags: true
    branch: master
